# Generated by Django 6.1 on 2026-08-12 17:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('claimed', 'Claimed'), ('approved', 'Approved'), ('expired', 'Expired'), ('rejected', 'Rejected')], db_index=True, default='claimed', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('paystack_recipient_code', models.CharField(blank=True, max_length=100)),
                ('transfer_code', models.CharField(blank=True, db_index=True, max_length=100)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('reward_type', models.CharField(db_index=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
