# Generated by Django 6.1 on 2026-08-12 17:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rewards', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='reward',
            index=models.Index(fields=['status', 'claimed_at'], name='rewards_rew_status_aca278_idx'),
        ),
        migrations.AddIndex(
            model_name='reward',
            index=models.Index(fields=['status', 'reward_type'], name='rewards_rew_status_09efd9_idx'),
        ),
    ]
