# Generated by Django 6.1 on 2026-08-12 17:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='postvideo',
            name='post',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='video', to='posts.post'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['user', 'created_at'], name='posts_post_user_id_34ab8c_idx'),
        ),
        migrations.AddIndex(
            model_name='postvideo',
            index=models.Index(fields=['status', 'created_at'], name='posts_postv_status_640f16_idx'),
        ),
    ]
